### ISSUE TITLE
Not sure if this is the right place...

### ISSUE THREAD

**Issue by TylerS1066** [misson20000/CBWrapper#2]
So after updating to the new dev build of CBWrapper, CBWrapper didn't have issues but my other plugins had issues, I don't know if you can/should/will fix these issues and if this is where I should bring these errors up but here the errors are:

**PwnFilter:** (spewed many of these out)
[Server thread/WARN]: [PwnFilter] Cached Player List is not equal to actual online player list!

**Essentials:** (spewed many of these out)
[Server thread/WARN]: [Essentials] Task #40 for Essentials vTeamCity generated an exception
java.lang.NullPointerException
	at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:99) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
	
	
**mcMMO on shutdown:**
[Server thread/ERROR]: Error occurred while disabling mcMMO v1.5.02-SNAPSHOT-b27 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.7.0_71]
	at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
	at com.gmail.nossr50.util.player.UserManager.saveAll(UserManager.java:55) ~[?:?]
	at com.gmail.nossr50.mcMMO.onDisable(mcMMO.java:216) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:333) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:81) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:700) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.jar:git-Spigot-2b97a38-e8efbb8]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

**Comment by misson20000** [comment]
Dang. I thought this might happen, and that's way too many plugins for me to deal with individually. There's a build in the works that should fix this coming out in the next few days.


Also, the best place to report any errors is to either PM me on BukkitDev or to comment on the overview page on BukkitDev: http://dev.bukkit.org/bukkit-plugins/cbwrapper/

**Comment by misson20000** [comment]
Fixed in CBWrapper 1.8.3 release
